### ISSUE TITLE
removing :padding fails to compile model

### ISSUE THREAD

**Issue by vans163** [elixir-nx/axon#216]
```elixir
    model = 
    Axon.input({nil, 1, 128, 128})
    |> Axon.conv(16, kernel_size: {3, 3}, activation: :relu)
    |> Axon.conv(16, kernel_size: {3, 3}, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2})
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(32, kernel_size: {3, 3}, activation: :relu)
    |> Axon.conv(32, kernel_size: {3, 3}, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2})
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(64, kernel_size: {3, 3}, activation: :relu)
    |> Axon.conv(64, kernel_size: {3, 3}, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2})
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(128, kernel_size: {3, 3}, activation: :relu)
    |> Axon.conv(128, kernel_size: {3, 3}, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2})
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(256, kernel_size: {3, 3}, activation: :relu)
    |> Axon.conv(256, kernel_size: {3, 3}, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2})
    |> Axon.dropout(rate: 0.2)
    |> Axon.flatten()
    |> Axon.dense(1024, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.5)
    |> Axon.dense(512, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.4)
    |> Axon.dense(256, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.3)
    |> Axon.dense(64, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.2)
    |> Axon.dense(2, activation: :softmax)
```
```
** (ArgumentError) window dimensions would result in empty tensor which is not currently supported in Nx, please open an issue if you'd like this behavior to change
    (nx 0.1.0) lib/nx/shape.ex:772: Nx.Shape.do_pool/4
    (nx 0.1.0) lib/nx/shape.ex:778: Nx.Shape.do_pool/4
    (nx 0.1.0) lib/nx/shape.ex:761: Nx.Shape.pool/5
    (axon 0.1.0-dev) lib/axon/shape.ex:1022: Axon.Shape.pool/6
    (axon 0.1.0-dev) lib/axon.ex:1065: Axon.pool/3
```

But this same model compiles with padding added
```elixir
    model = 
    Axon.input({nil, 1, 128, 128})
    |> Axon.conv(16, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.conv(16, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2}, padding: :same)
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(32, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.conv(32, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2}, padding: :same)
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(64, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.conv(64, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2}, padding: :same)
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(128, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.conv(128, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2}, padding: :same)
    |> Axon.dropout(rate: 0.2)
    |> Axon.conv(256, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.conv(256, kernel_size: {3, 3}, padding: :same, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.max_pool(kernel_size: {2, 2}, padding: :same)
    |> Axon.dropout(rate: 0.2)
    |> Axon.flatten()
    |> Axon.dense(1024, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.5)
    |> Axon.dense(512, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.4)
    |> Axon.dense(256, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.3)
    |> Axon.dense(64, activation: :relu)
    |> Axon.batch_norm()
    |> Axon.dropout(rate: 0.2)
    |> Axon.dense(2, activation: :softmax)
```

**Comment by seanmor5** [comment]
Ahhh so this is happening because the model spatial dims would be `0` because the default padding is `:valid`. The error message is just bad, you shouldn't even be able to build a model like this. I will update the error so it occurs earlier

**Comment by seanmor5** [comment]
This was actually an upstream Nx bug which has been fixed and Axon has been updated
