### ISSUE TITLE
RNN `lstm` trainer not working

### ISSUE THREAD

**Issue by alisinabh** [elixir-nx/axon#251]
I was not able to make the LSTM layer work. I have the following code

```elixir
...
model =
  Axon.input({nil, sequence_length, 1})
  |> Axon.lstm(256)
  |> elem(1)
  |> Axon.dropout(rate: 0.2)
  |> Axon.dense(vocab_count, activation: :softmax)

params =
  model
  |> Axon.Loop.trainer(:categorical_cross_entropy, :adam)
  |> Axon.Loop.run(Stream.zip(training_batches, result_batches), epochs: 1)
```

and I get the error:

```
no match of right hand side value: %{prediction: {#Nx.Tensor<
     f32[1][1][256]
     
     Nx.Defn.Expr
     parameter a:1   f32[1][1][256]
   >, #Nx.Tensor<
     f32[1][1][256]
     
     Nx.Defn.Expr
     parameter a:2   f32[1][1][256]
   >}, state: %{}}

    (axon 0.1.0-dev) lib/axon/recurrent.ex:69: Axon.Recurrent."__defn:lstm_cell__"/7
    (axon 0.1.0-dev) lib/axon/recurrent.ex:176: anonymous fn/3 in Axon.Recurrent."__defn:dynamic_unroll__"/6
    (nx 0.2.0) lib/nx/defn/expr.ex:279: Nx.Defn.Expr.defn_while/5
    (axon 0.1.0-dev) lib/axon/recurrent.ex:172: Axon.Recurrent."__defn:dynamic_unroll__"/6
    (axon 0.1.0-dev) lib/axon/compiler.ex:834: Axon.Compiler.recur_predict_fun/5
    (axon 0.1.0-dev) lib/axon/compiler.ex:182: Axon.Compiler.to_predict_fun/5
    (elixir 1.13.4) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (axon 0.1.0-dev) lib/axon/compiler.ex:225: Axon.Compiler.recur_predict_fun/5
```

Which was easy to fix by changing line 69 in `recurrent.ex` to `%{prediction: {cell, hidden}} = carry` but the I get this error from the while do block in `recurrent.ex`:

```
** (Axon.CompilerError) error while building prediction for lstm:

** (CompileError) /home/alisina/Projects/axon/lib/axon/recurrent.ex:172: 
the do-block in while must return the shape, type, and names as the initial arguments. Got body {s64, {f32[1][1][256], f32[1][1][256]}, f32[1][100][256], f32[1][100][1], {f32[1][256], f32[1][256], f32[1][256], f32[1][256]}, {f32[256][256], f32[256][256], f32[256][256], f32[256][256]}, {f32[256], f32[256], f32[256], f32[256]}} and initial {s64, %{:prediction => {f32[1][1][256], f32[1][1][256]}, :state => %{}}, f32[1][100][256], f32[1][100][1], {f32[1][256], f32[1][256], f32[1][256], f32[1][256]}, {f32[256][256], f32[256][256], f32[256][256], f32[256][256]}, {f32[256], f32[256], f32[256], f32[256]}}
```

I'm not quite sure if this is a bug or I'm doing something wrong.

### Update
I was able to fix the issue with changing the following line but I don't think it is the right approach.

```diff
# lib/axon/compiler.ex:814
     input = safe_as_type(res, compute)
-    carry = deep_new(hidden_state, &safe_as_type(&1, compute))
+    carry =
+      case deep_new(hidden_state, &safe_as_type(&1, compute)) do
+        %{prediction: carry} -> carry
+        carry -> carry
+      end
```

**Comment by seanmor5** [comment]
@alisinabh Can you retry your code without the applied fixes on `main`? I recently pushed some compiler updates that might have broken this more or fixed it :D

Thank you for all your work making Axon better!

**Comment by alisinabh** [comment]
@seanmor5 Yes it is working now without any errors both on the train stage and prediction. I will close this.

My pleasure. I will be happy to learn and help. :green_heart:
