### ISSUE TITLE
Nx `0.2.1` issue with LSTM, GRU and custom layers

### ISSUE THREAD

**Issue by alisinabh** [elixir-nx/axon#269]
With Nx `0.2.1` it is not possible to construct models which have LSTM, GRU or custom layers and many other things. 
You can visit #268 CI logs for detailed info.

### Example

```elixir
iex> Axon.input({nil, 32, 10}) |> Axon.lstm(64)
** (ArgumentError) cannot pass a tensor expression as argument to defn, got: #Nx.Tensor<
  f32[1][32][10]
  
  Nx.Defn.Expr
  parameter a:0   f32[1][32][10]
>
    (nx 0.2.1) lib/nx/defn/composite.ex:168: anonymous fn/2 in Nx.Defn.Composite.flatten_runtime_args/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (nx 0.2.1) lib/nx/defn/composite.ex:167: Nx.Defn.Composite.flatten_runtime_args/2
    (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (nx 0.2.1) lib/nx/defn/compiler.ex:104: Nx.Defn.Compiler.runtime/3
    (nx 0.2.1) lib/nx/defn/compiler.ex:90: Nx.Defn.Compiler.__jit__/3
    (nx 0.2.1) lib/nx/defn.ex:278: Nx.Defn.jit/3
    (axon 0.1.0-dev) lib/axon.ex:236: Axon.infer_shape/3
```

**Comment by seanmor5** [comment]
Fixed on main
