### ISSUE TITLE
Axon.Display.as_table(model, x_test) gives error when using LSTM models with .then in them

### ISSUE THREAD

**Issue by danieljaouen** [elixir-nx/axon#388]
I am not sure if the cause is strictly because of the `then`s, but I do see an error.  Here is my model: 

```elixir
input = Axon.input("input", shape: {prediction_days, 1})

model =
  input
  |> Axon.lstm(50)
  |> then(fn {seq, _} -> seq end)
  |> Axon.dropout(rate: 0.2)
  |> Axon.lstm(50)
  |> then(fn {seq, _} -> seq end)
  |> Axon.dropout(rate: 0.2)
  |> Axon.lstm(50)
  |> then(fn {seq, _} -> seq end)
  |> Axon.dropout(rate: 0.2)
  |> Axon.dense(1, activation: :sigmoid)
```

And here is my prediction code:
```elixir
params =
  model
  |> Axon.Loop.trainer(:mean_squared_error, :adam)
  |> Axon.Loop.metric(:mean_absolute_error, "MAE")
  |> Axon.Loop.run(Stream.zip(batched_x_train, batched_y_train), %{}, epochs: 25, compiler: EXLA)

Axon.Display.as_table(model, x_test) |> IO.puts

y_pred = Nx.add(price_min_series, Nx.multiply(scale, y_pred))
```

And here is the error:

```
** (BadFunctionError) expected a function, got: {:tuple, [#Function<49.132341458/2 in Axon.lstm/4>, #Function<49.132341458/2 in Axon.lstm/4>, #Function<49.132341458/2 in Axon.lstm/4>, #Function<49.132341458/2 in Axon.lstm/4>]}
    (axon 0.2.0) lib/axon/display.ex:215: anonymous fn/2 in Axon.Display.render_parameters/2
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (axon 0.2.0) lib/axon/display.ex:214: Axon.Display.render_parameters/2
    (axon 0.2.0) lib/axon/display.ex:189: Axon.Display.do_axon_to_rows/6
    (axon 0.2.0) lib/axon/display.ex:86: Axon.Display.axon_to_rows/6
    (axon 0.2.0) lib/axon/display.ex:152: anonymous fn/4 in Axon.Display.do_axon_to_rows/6
    (elixir 1.14.0) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

I should note that I encountered this when trying to debug why my prediction tensor had the same dimensions as my input tensor (which was `60 x 60 x 1`.  

I have also uploaded the whole Livebook to GitHub, in case you want to try it out yourself (it will require an Alpha Vantage API key, which is free): https://github.com/danieljaouen/livebook-axon-test/blob/main/testing-axon-and-vegalite.livemd

**Comment by seanmor5** [comment]
Fixed in 2f8c4fd2eedcf7600e346c5e4752970f4010d20c

<detail>
```
iex(15)> Axon.Display.as_table(model, Nx.random_uniform({60, 60, 1})) |> IO.puts
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                           Model                                                                                                                                           |
+======================================================================================+==============================================+============================================+=====================+==================================================================================+
| Layer                                                                                | Input Shape                                  | Output Shape                               | Options             | Parameters                                                                       |
+======================================================================================+==============================================+============================================+=====================+==================================================================================+
| input ( input )                                                                      | []                                           | {60, 60, 1}                                | shape: {60, 60, 1}  |                                                                                  |
|                                                                                      |                                              |                                            | optional: false     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm__c_hidden_state ( recurrent_state["input"] )                                    | [{60, 60, 1}]                                | {60, 1, 50}                                | key: #Nx.Tensor<    |                                                                                  |
|                                                                                      |                                              |                                            |   u32[2]            |                                                                                  |
|                                                                                      |                                              |                                            |                     |                                                                                  |
|                                                                                      |                                              |                                            |   Nx.Defn.Expr      |                                                                                  |
|                                                                                      |                                              |                                            |   tensor a   u32[2] |                                                                                  |
|                                                                                      |                                              |                                            | >                   |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm__h_hidden_state ( recurrent_state["input"] )                                    | [{60, 60, 1}]                                | {60, 1, 50}                                | key: #Nx.Tensor<    |                                                                                  |
|                                                                                      |                                              |                                            |   u32[2]            |                                                                                  |
|                                                                                      |                                              |                                            |                     |                                                                                  |
|                                                                                      |                                              |                                            |   Nx.Defn.Expr      |                                                                                  |
|                                                                                      |                                              |                                            |   tensor a   u32[2] |                                                                                  |
|                                                                                      |                                              |                                            | >                   |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm__hidden_state ( container {"lstm__c_hidden_state", "lstm__h_hidden_state"} )    | {}                                           | {{60, 1, 50}, {60, 1, 50}}                 |                     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_0 ( lstm["input", "lstm__hidden_state"] )                                       | [{60, 60, 1}, {{60, 1, 50}, {60, 1, 50}}]    | {{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}} | activation: :tanh   | input_kernel: tuple{"f32[1][50]", "f32[1][50]", "f32[1][50]", "f32[1][50]"}      |
|                                                                                      |                                              |                                            | gate: :sigmoid      | hidden_kernel: tuple{"f32[50][50]", "f32[50][50]", "f32[50][50]", "f32[50][50]"} |
|                                                                                      |                                              |                                            | unroll: :dynamic    | bias: tuple{"f32[50]", "f32[50]", "f32[50]", "f32[50]"}                          |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_1_output_sequence ( elem["lstm_0"] )                                            | [{{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}}] | {60, 60, 50}                               |                     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| dropout_0 ( dropout["lstm_1_output_sequence"] )                                      | [{60, 60, 50}]                               | {60, 60, 50}                               | rate: 0.2           |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_1_c_hidden_state ( recurrent_state["dropout_0"] )                               | [{60, 60, 50}]                               | {60, 1, 50}                                | key: #Nx.Tensor<    |                                                                                  |
|                                                                                      |                                              |                                            |   u32[2]            |                                                                                  |
|                                                                                      |                                              |                                            |                     |                                                                                  |
|                                                                                      |                                              |                                            |   Nx.Defn.Expr      |                                                                                  |
|                                                                                      |                                              |                                            |   tensor a   u32[2] |                                                                                  |
|                                                                                      |                                              |                                            | >                   |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_1_h_hidden_state ( recurrent_state["dropout_0"] )                               | [{60, 60, 50}]                               | {60, 1, 50}                                | key: #Nx.Tensor<    |                                                                                  |
|                                                                                      |                                              |                                            |   u32[2]            |                                                                                  |
|                                                                                      |                                              |                                            |                     |                                                                                  |
|                                                                                      |                                              |                                            |   Nx.Defn.Expr      |                                                                                  |
|                                                                                      |                                              |                                            |   tensor a   u32[2] |                                                                                  |
|                                                                                      |                                              |                                            | >                   |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_1_hidden_state ( container {"lstm_1_c_hidden_state", "lstm_1_h_hidden_state"} ) | {}                                           | {{60, 1, 50}, {60, 1, 50}}                 |                     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_1 ( lstm["dropout_0", "lstm_1_hidden_state"] )                                  | [{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}]   | {{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}} | activation: :tanh   | input_kernel: tuple{"f32[50][50]", "f32[50][50]", "f32[50][50]", "f32[50][50]"}  |
|                                                                                      |                                              |                                            | gate: :sigmoid      | hidden_kernel: tuple{"f32[50][50]", "f32[50][50]", "f32[50][50]", "f32[50][50]"} |
|                                                                                      |                                              |                                            | unroll: :dynamic    | bias: tuple{"f32[50]", "f32[50]", "f32[50]", "f32[50]"}                          |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_2_output_sequence ( elem["lstm_1"] )                                            | [{{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}}] | {60, 60, 50}                               |                     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| dropout_1 ( dropout["lstm_2_output_sequence"] )                                      | [{60, 60, 50}]                               | {60, 60, 50}                               | rate: 0.2           |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_2_c_hidden_state ( recurrent_state["dropout_1"] )                               | [{60, 60, 50}]                               | {60, 1, 50}                                | key: #Nx.Tensor<    |                                                                                  |
|                                                                                      |                                              |                                            |   u32[2]            |                                                                                  |
|                                                                                      |                                              |                                            |                     |                                                                                  |
|                                                                                      |                                              |                                            |   Nx.Defn.Expr      |                                                                                  |
|                                                                                      |                                              |                                            |   tensor a   u32[2] |                                                                                  |
|                                                                                      |                                              |                                            | >                   |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_2_h_hidden_state ( recurrent_state["dropout_1"] )                               | [{60, 60, 50}]                               | {60, 1, 50}                                | key: #Nx.Tensor<    |                                                                                  |
|                                                                                      |                                              |                                            |   u32[2]            |                                                                                  |
|                                                                                      |                                              |                                            |                     |                                                                                  |
|                                                                                      |                                              |                                            |   Nx.Defn.Expr      |                                                                                  |
|                                                                                      |                                              |                                            |   tensor a   u32[2] |                                                                                  |
|                                                                                      |                                              |                                            | >                   |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_2_hidden_state ( container {"lstm_2_c_hidden_state", "lstm_2_h_hidden_state"} ) | {}                                           | {{60, 1, 50}, {60, 1, 50}}                 |                     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_2 ( lstm["dropout_1", "lstm_2_hidden_state"] )                                  | [{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}]   | {{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}} | activation: :tanh   | input_kernel: tuple{"f32[50][50]", "f32[50][50]", "f32[50][50]", "f32[50][50]"}  |
|                                                                                      |                                              |                                            | gate: :sigmoid      | hidden_kernel: tuple{"f32[50][50]", "f32[50][50]", "f32[50][50]", "f32[50][50]"} |
|                                                                                      |                                              |                                            | unroll: :dynamic    | bias: tuple{"f32[50]", "f32[50]", "f32[50]", "f32[50]"}                          |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| lstm_3_output_sequence ( elem["lstm_2"] )                                            | [{{60, 60, 50}, {{60, 1, 50}, {60, 1, 50}}}] | {60, 60, 50}                               |                     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| dropout_2 ( dropout["lstm_3_output_sequence"] )                                      | [{60, 60, 50}]                               | {60, 60, 50}                               | rate: 0.2           |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| dense_0 ( dense["dropout_2"] )                                                       | [{60, 60, 50}]                               | {60, 60, 1}                                |                     | kernel: f32[50][1]                                                               |
|                                                                                      |                                              |                                            |                     | bias: f32[1]                                                                     |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
| sigmoid_0 ( sigmoid["dense_0"] )                                                     | [{60, 60, 1}]                                | {60, 60, 1}                                |                     |                                                                                  |
+--------------------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------+---------------------+----------------------------------------------------------------------------------+
Total Parameters: 50851
Total Parameters Memory: 203404 bytes
```
</detail>

Btw, I am guessing you're trying to translate a model from Keras which is where the shape confusion is coming from. The difference is that Keras LSTM's by default return the last token of the transformed input unless `return_sequences=True`. I think what you want is to add the following before your last dense layer:

```elixir
# slices out LSTM last token
|> Axon.nx(fn x -> Nx.squeeze(x[[0..-1//1, -1, 0..-1//1]], axes: [1]) end)
```

And you will get what you're looking for

**Comment by danieljaouen** [comment]
Thans, @seanmor5!

**Comment by josevalim** [comment]
If you are using Elixir v1.14 you can do:

```
|> Axon.nx(fn x -> Nx.squeeze(x[[.., -1, ..]], axes: [1]) end)
```

Which is a bit easier on the eyes. :)
