### ISSUE TITLE
Can't pass multiple inputs in custom trainer functions

### ISSUE THREAD

**Issue by bartekupartek** [elixir-nx/axon#582]
I need to add two inputs to my model, the first input should take samples from training data set, the second input should take a timestep by which I'll need to calculate time projection later on, I stuck trying to pass second input in custom init function or directly to predict_fn. 
The model below doesn't make sense I simplified my example to pass just a random tensor as a timestep input:

```
Mix.install([
  {:axon, "== 0.6.1"},
  {:kino, ">= 0.9.0"},
  {:scidata, "~> 0.1"}
])
```
```
defmodule MyModel do
  import Nx.Defn

  def model do
    sample_shape = {12, 32, 32, 3}
    sample = Axon.input("sample", shape: sample_shape)
    timestep = Axon.input("timestep", shape: {})
    
    time_emb = Axon.layer(&t_emb/2, [timestep], embedding_size: 128)

    Axon.conv(sample, 32,
      kernel_size: 3,
      padding: [{1, 1}, {1, 1}],
      name: "input_conv",
      activation: :silu
    )
    |> Axon.add(time_emb)
  end

  defn t_emb(timestep, _opts) do
    print_expr(timestep, label: :temestemp?)

    timestep
  end

  deftransform sample_timesteps(_random_key) do
    new_key = Nx.Random.key(123)
    timestep = Nx.iota({1, 32, 32, 3}, names: [:n, :time_x, :time_y, :d])
    {timestep, new_key}
  end
end
```

```
out = MyModel.model()
Axon.get_inputs(out) |> IO.inspect()
```
`%{"sample" => {12, 32, 32, 3}, "timestep" => {}}`

```
{init_fn, predict_fn} = Axon.build(out)
{optimizer_init, optimizer} = Polaris.Optimizers.adamw(learning_rate: 1.0e-4)
import Nx.Defn

init = fn template, _state ->
  template = %{
    "sample" => Nx.template({12, 32, 32, 3}, :f32),
    "timestep" => Nx.template({}, :f32)
  }

  params = init_fn.(template, %{})
  key = Nx.Random.key(123)

  %{
    key: key,
    i: Nx.tensor(0),
    model_state: params,
    optimizer_state: optimizer_init.(params),
    loss: Nx.tensor(0.0)
  }
end

step = fn batch, state ->
  iter = state[:i]
  params = state[:model_state]
  key = state[:key]
  {t, key} = MyModel.sample_timesteps(key)
  noise = batch * t

  {loss, grads} =
    value_and_grad(params, fn params ->
      %{prediction: preds} =
        predict_fn.(params, %{
          "sample" => batch,
          "timestep" => t
        })

      Axon.Losses.categorical_cross_entropy(preds, noise, reduction: :mean)
    end)

  optimizer_state = state[:optimizer_state]

  {updates, optimizer_state} = optimizer.(grads, optimizer_state, params)
  params = Polaris.Updates.apply_updates(params, updates)

  new_loss =
    state[:loss]
    |> Nx.multiply(state[:i])
    |> Nx.add(loss)
    |> Nx.divide(Nx.add(state[:i], 1))

  %{
    key: key,
    iteration: iter + 1,
    model_state: params,
    optimizer_state: optimizer_state,
    loss: new_loss
  }
end

batch_size = 12

{{data, type, shape}, _train_labels} = Scidata.CIFAR100.download()
IO.inspect(shape, label: :dataset_shape)

shape = {:auto, 32, 32, 3}

train_data =
  data
  |> Nx.from_binary(type)
  |> Nx.reshape(shape, names: [:images, :height, :width, :channels])
  |> Nx.divide(255)
  |> Nx.to_batched(batch_size)

step
|> Axon.Loop.loop(init)
|> Axon.Loop.run(train_data, %{}, iterations: 10)
```

The issue with a template in init function:
```
** (Axon.CompileError) exception found when compiling layer Axon.Layers.conv/4 named input_conv:

    ** (RuntimeError) cannot perform operations on a Nx.TemplateBackend tensor
        (nx 0.7.2) lib/nx/template_backend.ex:31: Nx.TemplateBackend.conv/4
        (nx 0.7.2) lib/nx.ex:13193: Nx.conv/3
        (axon 0.6.1) lib/axon/layers.ex:364: Axon.Layers."__defn:conv_impl__"/4
    

(pass debug: true to build/compile see where the layer was defined)


Compiling of the model was initiated at:

    #cell:c7byoosengyhscek:11: (file)
    #cell:c7byoosengyhscek:67: (file)
 ```
    
when I comment this lines from init_fn to pass actual input:
```
# template = %{
#     "sample" => Nx.template({12, 32, 32, 3}, :f32),
#     "timestep" => Nx.template({}, :f32)
#   }
````
I'm getting an image input in place of timestep:
```
temestemp?: #Nx.Tensor<
  f32[images: 12][height: 32][width: 32][channels: 3]
  
  Nx.Defn.Expr
  parameter a:0   f32[12][32][32][3]
>
temestemp?: #Nx.Tensor<
  f32[images: 12][height: 32][width: 32][channels: 3]
  
  Nx.Defn.Expr
  parameter a:0   f32[12][32][32][3]
>

```
I'd like to see `[:n, :time_x, :time_y, :d]` named tensor in the log
  
Please let me know if I'm doing it wrong or is it a bug? I stuck on this for almost a week before I discovered my timestep input isn't even a timestep

**Comment by seanmor5** [comment]
There is definitely something strange going on here. So when you initialize a model, you need to provide all of the inputs and their shape. So if you remove your logic:

```elixir
template = %{
  "sample" => Nx.template({12, 32, 32, 3}, :f32),
  "timestep" => Nx.template({}, :f32)
}
```

It actually should just blow up because you're giving it 1 input. I think the issue though is that if you pass a tensor it will just assume that input should be used for *every* input in the model, and so it doesn't raise. So that is 1 Axon bug.

As for the issues with templates, you should use a tensor there instead. I know it's confusing, but the issue is basically that you are using templates *inside* of a numerical definition. They are only meant to be used as placeholder parameters outside of numerical definitions. So I can use:

```elixir
  template = %{
    "sample" => template,
    "timestep" => Nx.tensor(1, type: :f32)
  }
```

To initialize the model and it works

**Comment by bartekupartek** [comment]
oh this is it! I can wrap more inputs in init_fn and the original template has only batch from the training dataset :+1: yeah it definitely clarified it, thank you!

**Comment by bartekupartek** [comment]
it looks like the first forward pass is `init_fn` where I though I could pas s just a template inputs without passing real data trough, this way I need to add noise to batched images in `init_fn` where I wanted to specify just a raw parameters :thinking:
