### ISSUE TITLE
Error trying to display model as a table

### ISSUE THREAD

**Issue by jakubpawlowicz** [elixir-nx/axon#600]
I took the example code from docs (https://elixir-nx.github.io/axon/Axon.html), i.e.

```elixir
Mix.install([
  {:axon, "~> 0.7"},
  {:exla, "~> 0.5"},
  {:table_rex, "~> 3.1.1"}
])

Nx.default_backend(EXLA.Backend)

model =
  Axon.input("input", shape: {nil, 784})
  |> Axon.dense(128, activation: :relu)
  |> Axon.batch_norm()
  |> Axon.dropout(rate: 0.8)
  |> Axon.dense(64)
  |> Axon.tanh()
  |> Axon.dense(10)
  |> Axon.activation(:softmax)

Axon.Display.as_table(model, Nx.template({1, 784}, :f32)) |> IO.puts
```

And this is giving me the following error:

```
** (FunctionClauseError) no function clause matching in Axon.Display.do_axon_to_rows/6

    The following arguments were given to Axon.Display.do_axon_to_rows/6:

        # 1
        %Axon.Node{id: 9, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: ~c"\b", parameters: [], args: [:layer], op: :softmax, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [], global_options: [], op_name: :softmax, meta: %{}, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 17]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}, {:elixir_lexical, :run, 3, [file: ~c"elixir_lexical.erl", line: 15]}]}

        # 2
        %{1 => %Axon.Node{id: 1, name: #Function<195.34494437/2 in Axon.name/2>, mode: :both, parent: [], parameters: [], args: [], op: :input, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [shape: {nil, 784}, optional: false], global_options: [], op_name: :input, meta: nil, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 10]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}, {:elixir_lexical, :run, 3, [file: ~c"elixir_lexical.erl", line: 15]}]}, 2 => %Axon.Node{id: 2, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: [1], parameters: [%Axon.Parameter{name: "kernel", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<3.39094922/3 in Axon.Initializers.glorot_uniform/1>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}, %Axon.Parameter{name: "bias", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<23.39094922/2 in Axon.Initializers.zeros/0>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}], args: [:layer, :parameter, :parameter], op: :dense, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [], global_options: [], op_name: :dense, meta: %{units: 128, use_bias: true}, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {Axon, :dense, 3, [file: ~c"lib/axon.ex", line: 877]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 11]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}]}, 3 => %Axon.Node{id: 3, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: [2], parameters: [], args: [:layer], op: :relu, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [], global_options: [], op_name: :relu, meta: %{}, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 11]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}, {:elixir_lexical, :run, 3, [file: ~c"elixir_lexical.erl", line: 15]}]}, 4 => %Axon.Node{id: 4, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: [3], parameters: [%Axon.Parameter{name: "gamma", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<3.39094922/3 in Axon.Initializers.glorot_uniform/1>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}, %Axon.Parameter{name: "beta", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<23.39094922/2 in Axon.Initializers.zeros/0>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}, %Axon.Parameter{name: "mean", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<23.39094922/2 in Axon.Initializers.zeros/0>, children: nil, type: {:f, 32}, frozen: false, kind: :state}, %Axon.Parameter{name: "var", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<11.39094922/2 in Axon.Initializers.ones/0>, children: nil, type: {:f, 32}, frozen: false, kind: :state}], args: [:layer, :parameter, :parameter, :parameter, :parameter], op: :batch_norm, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [epsilon: 1.0e-5, channel_index: -1, momentum: 0.1], global_options: [], op_name: :batch_norm, meta: nil, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 12]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}, {:elixir_lexical, :run, 3, [file: ~c"elixir_lexical.erl", line: 15]}]}, 5 => %Axon.Node{id: 5, name: #Function<194.34494437/2 in Axon.name/2>, mode: :train, parent: [4], parameters: [%Axon.Parameter{name: "key", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<160.34494437/2 in Axon.dropout/3>, children: nil, type: {:f, 32}, frozen: false, kind: :state}], args: [:layer, :parameter], op: :dropout, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [rate: 0.8], global_options: [], op_name: :dropout, meta: nil, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 13]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}, {:elixir_lexical, :run, 3, [file: ~c"elixir_lexical.erl", line: 15]}]}, 6 => %Axon.Node{id: 6, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: [5], parameters: [%Axon.Parameter{name: "kernel", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<3.39094922/3 in Axon.Initializers.glorot_uniform/1>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}, %Axon.Parameter{name: "bias", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<23.39094922/2 in Axon.Initializers.zeros/0>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}], args: [:layer, :parameter, :parameter], op: :dense, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [], global_options: [], op_name: :dense, meta: %{units: 64, use_bias: true}, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {Axon, :dense, 3, [file: ~c"lib/axon.ex", line: 877]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 14]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}]}, 7 => %Axon.Node{id: 7, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: [6], parameters: [], args: [:layer], op: :tanh, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [], global_options: [], op_name: :tanh, meta: %{}, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 15]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}, {:elixir_lexical, :run, 3, [file: ~c"elixir_lexical.erl", line: 15]}]}, 8 => %Axon.Node{id: 8, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: ~c"\a", parameters: [%Axon.Parameter{name: "kernel", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<3.39094922/3 in Axon.Initializers.glorot_uniform/1>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}, %Axon.Parameter{name: "bias", template: #Function<486.34494437/1 in Axon.shape_fun/2>, shape: nil, initializer: #Function<23.39094922/2 in Axon.Initializers.zeros/0>, children: nil, type: {:f, 32}, frozen: false, kind: :parameter}], args: [:layer, :parameter, :parameter], op: :dense, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [], global_options: [], op_name: :dense, meta: %{units: 10, use_bias: true}, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {Axon, :dense, 3, [file: ~c"lib/axon.ex", line: 877]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 16]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}]}, 9 => %Axon.Node{id: 9, name: #Function<194.34494437/2 in Axon.name/2>, mode: :both, parent: ~c"\b", parameters: [], args: [:layer], op: :softmax, policy: #Axon.MixedPrecision.Policy<>, hooks: [], opts: [], global_options: [], op_name: :softmax, meta: %{}, stacktrace: [{Axon, :layer, 3, [file: ~c"lib/axon.ex", line: 346]}, {:elixir_compiler_0, :__FILE__, 1, [file: ~c"display.exs", line: 17]}, {:elixir_compiler, :dispatch, 4, [file: ~c"elixir_compiler.erl", line: 67]}, {:elixir_compiler, :compile, 4, [file: ~c"elixir_compiler.erl", line: 52]}, {:elixir_compiler, :maybe_fast_compile, 3, [file: ~c"elixir_compiler.erl", line: 39]}, {:elixir_lexical, :run, 3, [file: ~c"elixir_lexical.erl", line: 15]}]}}

        # 3
        #Nx.Tensor<
          f32[1][784]
          Nx.TemplateBackend
        >

        # 4
        %{}

        # 5
        %{}

        # 6
        %{num_params: 0, total_param_byte_size: 0}

    Attempted function clauses (showing 2 out of 2):

        defp do_axon_to_rows(%Axon.Node{id: id, op: structure, op_name: :container, parent: [parents], name: name_fn}, nodes, templates, cache, op_counts, model_info)
        defp do_axon_to_rows(%Axon.Node{
      id: id,
      parent: parents,
      parameters: params,
      name: name_fn,
      opts: opts,
      policy: %{params: {_, bitsize}},
      op_name: op_name
    }, nodes, templates, cache, op_counts, model_info)

    (axon 0.7.0) lib/axon/display.ex:93: Axon.Display.do_axon_to_rows/6
    (axon 0.7.0) lib/axon/display.ex:85: Axon.Display.axon_to_rows/6
    (axon 0.7.0) lib/axon/display.ex:39: Axon.Display.as_table/2
    display.exs:21: (file)
```

Any clues what's going on here?

**Comment by seanmor5** [comment]
Fixed in main!

**Comment by jakubpawlowicz** [comment]
Confirmed it works! Thanks for a quick turnaround :100:
